### ISSUE TITLE
invoice_details route missing from ln-service

### ISSUE THREAD

**Issue by johncantrell97** [submarineswaps/swaps-service#64]
I'm trying to run swaps-service locally and when I paste in a yalls.org invoice it tells me it is invalid.  When I check swaps-service logs I can see it tries to make a GET request to /api/v0/invoice_details/ltctestnet/<invoice> and I'm getting a HTTP 503 error response.  I tried looking in ln-service/server.js file and it does not look like that route is setup? Are additional routes setup somewhere else in ln-service? If so, any idea why I might be seeing this error?

**Comment by alexbosworth** [comment]
Is that the complete request? The router is setup here: https://github.com/submarineswaps/swaps-service/blob/master/routers/api.js#L47

**Comment by johncantrell97** [comment]
Seeing this when I paste in the invoice:

[ 503,
  'UnexpectedQueryRoutesError',
  { Error: 14 UNAVAILABLE: Connect Failed
    at Object.exports.createStatusError (/Users/jamespeerless/Development/swaps-service/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/Users/jamespeerless/Development/swaps-service/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/Users/jamespeerless/Development/swaps-service/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/jamespeerless/Development/swaps-service/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/Users/jamespeerless/Development/swaps-service/node_modules/grpc/src/client_interceptors.js:841:24)
    code: 14,
    metadata: Metadata { _internal_repr: {} },
    details: 'Connect Failed' } ]
GET /api/v0/invoice_details/testnet/lntb1500n1pd56esxpp52ys6rsjuc8au0w0za9lvazzch64csnsfjxa970y5lr42ykchqekqdp6g9jxggrjv4skxarfdahzpuyl3kazqar0ypuk7atjyp3k7mrvv43hg6t0dccqzys6rcurze77g2q9zm57l2tzxmp6h67fmskqaxjnuatvh6gh35k5vzx83gk3apvyeyhcesn62f3t4deu5a97mca5qm24wjhvssyrfps23qqc23mrc 503 81.161 ms - 26



Unrelated question, why does the on-chain token network matter when getting invoice details? Shouldn't the only thing that matter what the off-chain network/token is?
